{% set name = "uproot3" %}
{% set version = "3.14.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/uproot3-{{ version }}.tar.gz
  sha256: 4396746ba5ef9071bb0a9da53294e4613a7f4548218940f86496e79d682d20eb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python =2.7|>=3.5
  run:
    - awkward0
    - cachetools
    - numpy >=1.13.1
    - python =2.7|>=3.5
    - uproot3-methods

test:
  imports:
    - uproot3
    - uproot3._connect
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/uproot3
  summary: ROOT I/O in pure Python and Numpy.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
